### PR TITLE
add missing instructions for ubuntu issues on installation (missing package)

### PR DESCRIPTION
**Pull request by noamoss**
adding the missing package:  libmemcached-dev

### CODE REVIEW

**Comment by niryariv** [comment]
Not merging:
1. This breaks compatibility for systems without apt-get installed (ie non-linux)
1. This isn't really part of the installation, in the same way that installing Python isn't in the README. 

A better approach would be to add a line saying "If you get an error like ... you might need to install libmemcache (for example ```apt get ...``` in Ubuntu")

**Comment by noamoss** [comment]
Is it better now?

**Comment by noamoss** [comment]
is it better?

**Comment by niryariv** [comment]
screen shot 2015-05-16 at 9 39 01 pm
???

**Comment by niryariv** [comment]
did you see the issue there? you've mistakenly added a bunch of unrelated files to the repo - we can go over this together on wednesday

**Comment by noamoss** [comment]
It was the virtualenv files. I thought it was needed and realized you don't
want it.

**Pull request closed without merging**
