### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by nathanIL**
Add _Docker_ support to ease the (mostly local for now...) deployment process.
Updated _readme.md_ with usage instructions.

### CODE REVIEW

**Comment by niryariv** [comment]
@alonisser any chance you can take a look? My Docker experience is lacking..

**Comment by alonisser** [comment]
I'll look soon



Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Comment by alonisser** [comment]
Nice work @nathanIL. Can be easier to setup if you already docker trained..
One question: Why fedora as base? I think we deploy to ubuntu ( @niryariv correct me if I'm wrong)

**Comment by nathanIL** [comment]
Hi Alon,

thanks. actually recent Linux distros are shipped with Docker, so following
the README.MD commands will get u up & running very easily.

why Fedora? only because I'm familiar with it somewhat more than Ubuntu. in
any case using Ubuntu instead is only a matter of changing the dependency
names & base image (FROM ....).

something else: do u plan to have an admin section for the server side?
could make it easier to manage Mongo / check redis stuff and get all admin
benefits on the way?

can use Flask-Admin as a base.
just a thought 😎

thanks,

**Comment by florpor** [comment]
Hey @nathanIL , good work, but it would be better if the base was Ubuntu (14.04) as it is what Heroku's cedar stack (which we deploy to) is based on.

As to the other question - there's no such plan right now. Data-wise our data is not supposed to be manually edited at all so there's no point for that, and monitoring wise (redis etc) there are dashboards that do that made by the Heroku addin providers.

**Pull request merged**
